package hibernate;
// Generated Dec 17, 2019 10:48:32 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * Administrators generated by hbm2java
 */
public class Administrators implements java.io.Serializable {

	private Integer adminid;
	private String username;
	private String password;

	public Administrators() {
	}

	public Administrators(Integer adminid) {
		this.adminid = adminid;
	}

	public Administrators(Integer adminid, String username, String password) {
		this.adminid = adminid;
		this.username = username;
		this.password = password;
	}

	public int getAdminid() {
		return this.adminid;
	}

	public void setAdminid(Integer adminid) {
		this.adminid = adminid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
