package hibernate;
// Generated Dec 17, 2019 10:48:32 AM by Hibernate Tools 4.3.5.Final

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private HistoryId id;
	private Users users;

	public History() {
	}

	public History(HistoryId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public HistoryId getId() {
		return this.id;
	}

	public void setId(HistoryId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
