package hibernate;
// Generated Dec 17, 2019 10:48:32 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * HistoryId generated by hbm2java
 */
public class HistoryId implements java.io.Serializable {

	private Integer userid;
	private Integer mid;
	private Timestamp viewtime;

	public HistoryId() {
	}

	public HistoryId(Integer userid, Integer mid, Timestamp viewtime) {
		this.userid = userid;
		this.mid = mid;
		this.viewtime = viewtime;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public Timestamp getViewtime() {
		return this.viewtime;
	}

	public void setViewtime(Timestamp viewtime) {
		this.viewtime = viewtime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryId))
			return false;
		HistoryId castOther = (HistoryId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this.getUserid() != null
				&& castOther.getUserid() != null && this.getUserid().equals(castOther.getUserid())))
				&& ((this.getMid() == castOther.getMid()) || (this.getMid() != null && castOther.getMid() != null
						&& this.getMid().equals(castOther.getMid())))
				&& ((this.getViewtime() == castOther.getViewtime()) || (this.getViewtime() != null
						&& castOther.getViewtime() != null && this.getViewtime().equals(castOther.getViewtime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result + (getMid() == null ? 0 : this.getMid().hashCode());
		result = 37 * result + (getViewtime() == null ? 0 : this.getViewtime().hashCode());
		return result;
	}

}
