package hibernate;
// Generated Dec 17, 2019 10:48:32 AM by Hibernate Tools 4.3.5.Final

/**
 * Similarity generated by hbm2java
 */
public class Similarity implements java.io.Serializable {

	private SimilarityId id;
	private Mediaitems mediaitemsByMid1;
	private Mediaitems mediaitemsByMid2;
	private Double similarity;

	public Similarity() {
	}

	public Similarity(SimilarityId id, Mediaitems mediaitemsByMid1, Mediaitems mediaitemsByMid2) {
		this.id = id;
		this.mediaitemsByMid1 = mediaitemsByMid1;
		this.mediaitemsByMid2 = mediaitemsByMid2;
	}

	public Similarity(SimilarityId id, Mediaitems mediaitemsByMid1, Mediaitems mediaitemsByMid2, Double similarity) {
		this.id = id;
		this.mediaitemsByMid1 = mediaitemsByMid1;
		this.mediaitemsByMid2 = mediaitemsByMid2;
		this.similarity = similarity;
	}

	public SimilarityId getId() {
		return this.id;
	}

	public void setId(SimilarityId id) {
		this.id = id;
	}

	public Mediaitems getMediaitemsByMid1() {
		return this.mediaitemsByMid1;
	}

	public void setMediaitemsByMid1(Mediaitems mediaitemsByMid1) {
		this.mediaitemsByMid1 = mediaitemsByMid1;
	}

	public Mediaitems getMediaitemsByMid2() {
		return this.mediaitemsByMid2;
	}

	public void setMediaitemsByMid2(Mediaitems mediaitemsByMid2) {
		this.mediaitemsByMid2 = mediaitemsByMid2;
	}

	public Double getSimilarity() {
		return this.similarity;
	}

	public void setSimilarity(Double similarity) {
		this.similarity = similarity;
	}

}
